package cmdlist_test

import (
	"path/filepath"
	"testing"

	"github.com/KEINOS/go-utiles/util"
	"github.com/Qithub-BOT/QiiTask/core/appinfo"
	"github.com/Qithub-BOT/QiiTask/qiitask/cmd/cmdlist"
	"github.com/Qithub-BOT/QiiTask/qiitask/cmd/cmdroot"
	"github.com/kami-zh/go-capturer"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNew(t *testing.T) {
	appInfo, err := appinfo.New(t.TempDir(), t.TempDir(), "")
	require.NoError(t, err)

	obj1 := cmdlist.New(appInfo)
	obj2 := cmdlist.New(appInfo)

	assert.NotSame(t, obj1, obj2, "it should not reference the same object")
}

func TestList(t *testing.T) {
	// Load global task (task under user home's config directory)
	pathDirApp := filepath.Join(util.GetPathDirRepo(), "testdata", "golden", "user_home_with_task")

	appInfo, err := appinfo.New(t.TempDir(), pathDirApp, "")
	require.NoError(t, err)

	mother := cmdroot.New(appInfo)
	mother.SetArgs([]string{
		"list",
		"--add-no-edit",
	})

	out := capturer.CaptureOutput(func() {
		require.NoError(t, mother.Execute())
	})

	expect := util.HereDoc(`
		// Code generated by QiiTask; DO NOT EDIT.
		+---+------------------------------------+
		| # | TITLE                              |
		+---+------------------------------------+
		| 1 | This is an un-done task in global. |
		+---+------------------------------------+
	`)

	assert.Equal(t, expect, out)
}

func TestList_empty_task(t *testing.T) {
	appInfo, err := appinfo.New(t.TempDir(), t.TempDir(), "")
	require.NoError(t, err)

	mother := cmdroot.New(appInfo)
	mother.SetArgs([]string{
		"list",
		"--add-no-edit",
	})

	out := capturer.CaptureOutput(func() {
		require.Error(t, mother.Execute())
	})

	assert.Contains(t, out, "まだタスクはありません")
}

type dataProvider []struct {
	option string
	expect string
}

var styleData = dataProvider{
	{
		option: "markdown",
		expect: util.HereDoc(`
		<!-- // Code generated by QiiTask; DO NOT EDIT. -->
		| # | title |
		| ---:| --- |
		| 1 | This is an un-done task in local (working dir) with conf in local. |
		`),
	},
	{
		option: "html",
		expect: util.HereDoc(`
		<!-- // Code generated by QiiTask; DO NOT EDIT. -->
		<table class="go-pretty-table">
		  <thead>
		  <tr>
		    <th align="right">#</th>
		    <th>title</th>
		  </tr>
		  </thead>
		  <tbody>
		  <tr>
		    <td align="right">1</td>
		    <td>This is an un-done task in local (working dir) with conf in local.</td>
		  </tr>
		  </tbody>
		</table>
		`),
	},
	{
		option: "csv",
		expect: "#,title\n1,This is an un-done task in local (working dir) with conf in local.\n",
	},
	{
		option: "color",
		expect: "// Code generated by QiiTask; DO NOT EDIT.\n" +
			"\x1b[44;37m # \x1b[0m\x1b[44;37m TITLE" +
			"                                                              \x1b[0m\n" +
			"\x1b[40;97m 1 \x1b[0m\x1b[40;97m This is an un-done task in local (working dir) with conf in local. \x1b[0m\n",
	},
}

func TestList_style(t *testing.T) {
	pathDirApp := filepath.Join(util.GetPathDirRepo(), "testdata", "golden", "working_with_task_and_conf")

	appInfo, err := appinfo.New(pathDirApp, t.TempDir(), "")
	require.NoError(t, err)

	mother := cmdroot.New(appInfo)

	for _, test := range styleData {
		mother.SetArgs([]string{
			"list",
			"--style",
			test.option,
			"--add-no-edit",
		})

		out := capturer.CaptureOutput(func() {
			require.NoError(t, mother.Execute())
		})

		assert.Equal(t, test.expect, out)
	}
}
