# Workflow for static analysis and lint via golangci-lint on any push to main.
# Details of this action see: https://github.com/golangci/golangci-lint-action
name: golangci-lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    if: ${{ !github.event.pull_request.draft }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --config ./.golangci.yml
